### ISSUE TITLE
TypeError: dispatcher.useSyncExternalStore is not a function

### ISSUE THREAD

**Issue by elmcapp** [microsoft/react-native-macos#1215]
### Environment

```markdown
"react": "18.0.0",
"react-native": "0.69.0",
"react-native-macos": "^0.66.0-0"
yarn 1.22.17
node v17.5.0
npm 8.4.1
Xcode 13
```

### Steps to reproduce the bug

Installed React Native for macOS with React Native 0.69. I got error:
TypeError: dispatcher.useSyncExternalStore is not a function. (In 'dispatcher.useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot)', 'dispatcher.useSyncExternalStore' is undefined)

### Expected Behavior

I expected React Native 0.69 as it did work with 0.68
